export const INITIATE_EVENTS_UPLOAD = "INITIATE_EVENTS_UPLOAD";
export const INITIATE_EVENTS_LIST = "INITIATE_EVENTS_LIST";
export const SET_EVENTS_LIST = "SET_EVENTS_LIST";
export const INITIATE_MY_EVENTS_LIST = "INITIATE_MY_EVENTS_LIST";
export const SET_MY_EVENTS_LIST = "SET_MY_EVENTS_LIST";
