export const INITIATE_MOMENT_UPLOAD = 'INITIATE_MOMENT_UPLOAD';
export const INITIATE_MOMENT_LIST = 'INITIATE_MOMENT_LIST';
export const SET_MOMENT_LIST = 'SET_MOMENT_LIST';
export const INITIATE_MY_MOMENT_LIST = 'INITIATE_MY_MOMENT_LIST';
export const SET_MY_MOMENT_LIST = 'SET_MY_MOMENT_LIST';
export const INITIATE_MOMENT_LIST_DETAILS = 'INITIATE_MOMENT_LIST_DETAILS';
export const SET_MOMENT_LIST_DETAILS = 'SET_MOMENT_LIST_DETAILS';