export const GET_PROFILE_BY_ID = "GET_PROFILE_BY_ID";
export const SET_PROFILE_BY_ID = "SET_PROFILE_BY_ID";
export const GET_PROFILE_NOTIFICATION = "GET_PROFILE_NOTIFICATION";
export const SET_PROFILE_NOTIFICATION = "SET_PROFILE_NOTIFICATION";
export const GET_PROFILE_MATCH_HISTORY = "GET_PROFILE_MATCH_HISTORY";
export const SET_PROFILE_MATCH_HISTORY = "SET_PROFILE_MATCH_HISTORY";
export const SEND_PROFILE_LIKE_COFFEE = "SEND_PROFILE_LIKE_COFFEE";
export const SET_PROFILE_LIKE_COFFEE_STATUS = "SET_PROFILE_LIKE_COFFEE_STATUS";
export const GET_PROFILE = "GET_PROFILE";
export const UPDATE_USER = "UPDATE_USER";
export const APPEARANCE_VERIFICATION = "APPEARANCE_VERIFICATION";
export const APPEARANCE_VERIFICATION_STATUS = "APPEARANCE_VERIFICATION_STATUS";
export const ADD_REQUEST_STATUS = "ADD_REQUEST_STATUS";
export const SET_REQUEST_STATUS = "SET_REQUEST_STATUS";
export const GET_PROFILE_PREFERENCES = "GET_PROFILE_PREFERENCES";
export const SET_PROFILE_PREFERENCES = "SET_PROFILE_PREFERENCES";
export const UPDATE_PROFILE_PREFERENCES = "UPDATE_PROFILE_PREFERENCES";
export const SET_UPDATE_PROFILE_PREFERENCES_STATUS =
    "SET_UPDATE_PROFILE_PREFERENCES_STATUS";

export const UPDATE_SEEN_STATUS = "UPDATE_SEEN_STATUS";
export const GET_COFFEE_COUPON = "GET_COFFEE_COUPON";
export const SET_COFFEE_COUPON = "SET_COFFEE_COUPON";
export const REDEEM_COUPON = "REDEEM_COUPON";
