export const INITIATE_VIBE_UPLOAD = "INITIATE_VIBE_UPLOAD";
export const INITIATE_VIBE_LIST = "INITIATE_VIBE_LIST";
export const SET_VIBE_LIST = "SET_VIBE_LIST";
export const INITIATE_MY_VIBE_LIST = "INITIATE_MY_VIBE_LIST";
export const SET_MY_VIBE_LIST = "SET_MY_VIBE_LIST";
export const INITIATE_VIBE_LIST_DETAILS = "INITIATE_VIBE_LIST_DETAILS";
export const SET_VIBE_LIST_DETAILS = "SET_VIBE_LIST_DETAILS";
export const HIDE_USER = "HIDE_USER";
export const BLOCK_USER = "BLOCK_USER";
export const FOLLOW_VIBES = "FOLLOW_VIBES";

export const GET_USER_VIBES_LIST = "GET_USER_VIBES_LIST";
export const SET_USER_VIBES_LIST = "SET_USER_VIBES_LIST";

export const GET_MATCHED_VIBES = "GET_MATCHED_VIBES";
export const SET_MATCHED_VIBES = "SET_MATCHED_VIBES";

export const SET_TAGS_SEARCH = "SET_TAGS_SEARCH";
export const GET_TAGS_SEARCH = "GET_TAGS_SEARCH";

export const SET_RECENT_SEARCH = "SET_RECENT_SEARCH";

export const FOLLOW_VIBE_USER = "FOLLOW_VIBE_USER";
export const UNFOLLOW_VIBE_UESR = "UNFOLLOW_VIBE_UESR";

export const GET_FOLLOWING_USER_LIST = "GET_FOLLOWING_USER_LIST";
export const SET_FOLLOWING_USER_LIST = "SET_FOLLOWING_USER_LIST";

export const SET_BLOCKED_USER_LIST = "SET_BLOCKED_USER_LIST";
export const GET_BLOCKED_USER_LIST = "GET_BLOCKED_USER_LIST";

export const UNBLOCK_USER = "UNBLOCK_USER";
export const REPORT_UESR = "REPORT_UESR";
