const products = [
  {
    artistId: "1234",
    artistName: "Harry",
    brandId: "1234",
    brandUrl: "/brand-123",
    brandLogo: "../../assets/images/brand-logo-3.svg",
    brandKor: "IAB Studio",
    brandEng: "IAB Studio",
    productId: "123",
    productImage: "https://s3.aws.com/123",
    productPrice: "12345",
    productCategory: ["cloth", "fashionItem"],
    productName: "NOIDA CUSTOMIZING"
  },
  {
    artistId: "1234",
    artistName: "Harry",
    brandId: "1234",
    brandUrl: "/brand-123",
    brandLogo: "../../assets/images/brand-logo-1.svg",
    brandKor: "IAB Studio",
    brandEng: "IAB Studio",
    productId: "124",
    productImage: "https://s3.aws.com/123",
    productPrice: "12345",
    productCategory: ["cloth", "fashionItem"],
    productName: "NOIDA CUSTOMIZING"
  },
  {
    artistId: "1234",
    artistName: "Harry",
    brandId: "1234",
    brandUrl: "/brand-123",
    brandLogo: "../../assets/images/brand-logo-1.svg",
    brandKor: "IAB Studio",
    brandEng: "IAB Studio",
    productId: "125",
    productImage: "https://s3.aws.com/123",
    productPrice: "12345",
    productCategory: ["cloth", "fashionItem"],
    productName: "NOIDA CUSTOMIZING"
  },
  {
    artistId: "1234",
    artistName: "Harry",
    brandId: "1234",
    brandUrl: "/brand-123",
    brandLogo: "../../assets/images/brand-logo-1.svg",
    brandKor: "IAB Studio",
    brandEng: "IAB Studio",
    productId: "126",
    productImage: "https://s3.aws.com/123",
    productPrice: "12345",
    productCategory: ["cloth", "fashionItem"],
    productName: "NOIDA CUSTOMIZING"
  },
  {
    artistId: "1234",
    artistName: "Harry",
    brandId: "1234",
    brandUrl: "/brand-123",
    brandLogo: "../../assets/images/brand-logo-1.svg",
    brandKor: "IAB Studio",
    brandEng: "IAB Studio",
    productId: "126",
    productImage: "https://s3.aws.com/123",
    productPrice: "12345",
    productCategory: ["cloth", "fashionItem"],
    productName: "NOIDA CUSTOMIZING"
  },
  {
    artistId: "1234",
    artistName: "Harry",
    brandId: "1234",
    brandUrl: "/brand-123",
    brandLogo: "../../assets/images/brand-logo-1.svg",
    brandKor: "IAB Studio",
    brandEng: "IAB Studio",
    productId: "126",
    productImage: "https://s3.aws.com/123",
    productPrice: "12345",
    productCategory: ["cloth", "fashionItem"],
    productName: "NOIDA CUSTOMIZING"
  },
  {
    artistId: "1234",
    artistName: "Harry",
    brandId: "1234",
    brandUrl: "/brand-123",
    brandLogo: "../../assets/images/brand-logo-1.svg",
    brandKor: "IAB Studio",
    brandEng: "IAB Studio",
    productId: "126",
    productImage: "https://s3.aws.com/123",
    productPrice: "12345",
    productCategory: ["cloth", "fashionItem"],
    productName: "NOIDA CUSTOMIZING"
  },
  {
    artistId: "1234",
    artistName: "Harry",
    brandId: "1234",
    brandUrl: "/brand-123",
    brandLogo: "../../assets/images/brand-logo-1.svg",
    brandKor: "IAB Studio",
    brandEng: "IAB Studio",
    productId: "126",
    productImage: "https://s3.aws.com/123",
    productPrice: "12345",
    productCategory: ["cloth", "fashionItem"],
    productName: "NOIDA CUSTOMIZING"
  }
];

export default products;
