export const tableData2 = [
  {
    id: '1',
    joinDate: '2019-01-01',
    joinStatus: '사용요청중',
    representativeEmail: 'exam@google.com',
    cinfirmDate: '2019-01-01',
    lawFirmID: 'lawfirm-kimpro',
    lawFirmName: '김프로 법무법인',
    representativeUser: '김변호사 이름 (Kim Pro)',
    usage: 'Disk : 128KB',
  },
  {
    id: '2',
    joinDate: '2019-01-01',
    representativeEmail: 'exam@google.com',
    joinStatus: '가입완료',
    cinfirmDate: '2019-01-01',
    lawFirmID: 'lawfirm-kimpro',
    lawFirmName: '김프로 법무법인',
    representativeUser: '김변호사 이름 (Kim Pro)',
    usage: 'Disk : 128KB',
  },
  {
    id: '3',
    joinDate: '2019-01-01',
    representativeEmail: 'exam@google.com',
    joinStatus: '가입완료',
    cinfirmDate: '2019-01-01',
    lawFirmID: 'lawfirm-kimpro',
    lawFirmName: '김프로 법무법인',
    representativeUser: '김변호사 이름 (Kim Pro)',
    usage: 'Disk : 128KB',
    _style: { backgroundColor: 'pink', fontWeight: 'bold' },
  },
  {
    id: '4',
    joinDate: '2019-01-01',
    representativeEmail: 'exam@google.com',
    joinStatus: '가입완료',
    cinfirmDate: '2019-01-01',
    lawFirmID: 'lawfirm-kimpro',
    lawFirmName: '김프로 법무법인',
    representativeUser: '김변호사 이름 (Kim Pro)',
    usage: 'Disk : 128KB',
  },
  {
    id: '5',
    joinDate: '2019-01-01',
    representativeEmail: 'exam@google.com',
    joinStatus: '가입완료',
    cinfirmDate: '2019-01-01',
    lawFirmID: 'lawfirm-kimpro',
    lawFirmName: '김프로 법무법인',
    representativeUser: '김변호사 이름 (Kim Pro)',
    usage: 'Disk : 128KB',
  },
  {
    id: '6',
    joinDate: '2019-01-01',
    representativeEmail: 'exam@google.com',
    joinStatus: '사용요청중',
    cinfirmDate: '2019-01-01',
    lawFirmID: 'lawfirm-kimpro',
    lawFirmName: '김프로 법무법인',
    representativeUser: '김변호사 이름 (Kim Pro)',
    usage: 'Disk : 128KB',
  },
];

export const tableData3 = [
  {
    id: '1',
    AccountGroup: '복리후생',
    Account: '회식비',
    Budget: 11000,
    AddBudget: 22000,
    Expense: 33000,
    AvailExpense: 44000,
    BudgetPercent: 55000,
  },
  {
    id: '2',
    AccountGroup: '복리후생',
    Account: '식대',
    Budget: 22000,
    AddBudget: 33000,
    Expense: 44000,
    AvailExpense: 55000,
    BudgetPercent: 66000,
  },
  {
    id: '3',
    AccountGroup: '복리후생',
    Account: '식대-기타',
    Budget: 33000,
    AddBudget: 44000,
    Expense: 55000,
    AvailExpense: 66000,
    BudgetPercent: 77000,
  },
  {
    id: '4',
    AccountGroup: '교육훈련비',
    Account: '해외출장비',
    Budget: 44000,
    AddBudget: 55000,
    Expense: 66000,
    AvailExpense: 77000,
    BudgetPercent: 88000,
  },
  {
    id: '5',
    AccountGroup: '교육훈련비',
    Account: '시내교통비',
    Budget: 55000,
    AddBudget: 66000,
    Expense: 77000,
    AvailExpense: 88000,
    BudgetPercent: 99000,
  },
];

export const excelImportTable = [
  {
    joinDate: '2019-01-01',
    joinStatus: '사용요청중',
    representativeEmail: 'exam@google.com',
    lawFirmID: 'lawfirm-kimpro',
    lawFirmName: '김프로 법무법인',
    representativeUser: '김변호사 이름 (Kim Pro)',
  },
  {
    joinDate: '2019-01-01',
    representativeEmail: 'exam@google.com',
    joinStatus: '가입완료',
    lawFirmID: 'lawfirm-kimpro',
    lawFirmName: '김프로 법무법인',
    representativeUser: '김변호사 이름 (Kim Pro)',
  },
  {
    joinDate: '2019-01-01',
    representativeEmail: 'exam@google.com',
    joinStatus: '가입완료',
    lawFirmID: 'lawfirm-kimpro',
    lawFirmName: '김프로 법무법인',
    representativeUser: '김변호사 이름 (Kim Pro)',
  },
  {
    joinDate: '2019-01-01',
    representativeEmail: 'exam@google.com',
    joinStatus: '가입완료',
    lawFirmID: 'lawfirm-kimpro',
    lawFirmName: '김프로 법무법인',
    representativeUser: '김변호사 이름 (Kim Pro)',
  },
  {
    joinDate: '2019-01-01',
    representativeEmail: 'exam@google.com',
    joinStatus: '가입완료',
    lawFirmID: 'lawfirm-kimpro',
    lawFirmName: '김프로 법무법인',
    representativeUser: '김변호사 이름 (Kim Pro)',
  },
  {
    joinDate: '2019-01-01',
    representativeEmail: 'exam@google.com',
    joinStatus: '사용요청중',
    lawFirmID: 'lawfirm-kimpro',
    lawFirmName: '김프로 법무법인',
    representativeUser: '김변호사 이름 (Kim Pro)',
  },
  {
    joinDate: '2019-01-01',
    representativeEmail: 'exam@google.com',
    joinStatus: '사용요청중',
    lawFirmID: 'lawfirm-kimpro',
    lawFirmName: '김프로 법무법인',
    representativeUser: '김변호사 이름 (Kim Pro)',
  },
  {
    joinDate: '2019-01-01',
    representativeEmail: 'exam@google.com',
    joinStatus: '사용요청중',
    lawFirmID: 'lawfirm-kimpro',
    lawFirmName: '김프로 법무법인',
    representativeUser: '김변호사 이름 (Kim Pro)',
  },
];
