// 고겍 관리
export const CUSTOMER_MNG_SET_REDUX_VALUES = 'CUSTOMER_MNG_SET_REDUX_VALUES';
export const CUSTOMER_MNG_SET_LIST_FETCH_CUSTOMER = 'CUSTOMER_MNG_SET_LIST_FETCH_CUSTOMER';
export const CUSTOMER_MNG_SET_LIST_FETCH_COMPANY = 'CUSTOMER_MNG_SET_LIST_FETCH_COMPANY';
export const CUSTOMER_MNG_SET_LIST_FETCH_COMPANY_MEMBER = 'CUSTOMER_MNG_SET_LIST_FETCH_COMPANY_MEMBER';
export const CUSTOMER_MNG_SET_LIST_FETCH_COMMON_COMPANY = 'CUSTOMER_MNG_SET_LIST_FETCH_COMMON_COMPANY';
export const CUSTOMER_MNG_SET_LIST_FETCH_INDIVIDUAL = 'CUSTOMER_MNG_SET_LIST_FETCH_INDIVIDUAL';
export const CUSTOMER_MNG_SET_DETAIL_BIND_CUSTOMER = 'CUSTOMER_MNG_SET_DETAIL_BIND_CUSTOMER';
export const CUSTOMER_MNG_SET_DETAIL_BIND_COMPANY = 'CUSTOMER_MNG_SET_DETAIL_BIND_COMPANY';
export const CUSTOMER_MNG_CHECK_INPUT_DATA_CUSTOMER = 'CUSTOMER_MNG_CHECK_INPUT_DATA_CUSTOMER';
export const CUSTOMER_MNG_CHECK_INPUT_DATA_COMPANY = 'CUSTOMER_MNG_CHECK_INPUT_DATA_COMPANY';
export const CUSTOMER_MNG_SAVE_DRAFT_CUSTOMER = 'CUSTOMER_MNG_SAVE_DRAFT_CUSTOMER';
export const CUSTOMER_MNG_SAVE_DRAFT_COMPANY = 'CUSTOMER_MNG_SAVE_DRAFT_COMPANY';
export const CUSTOMER_MNG_HANDLE_DATA_COMPANY_MEMBER = 'CUSTOMER_MNG_HANDLE_DATA_COMPANY_MEMBER';
export const CUSTOMER_MNG_HANDLE_DATA_INDIVIDUAL = 'CUSTOMER_MNG_HANDLE_DATA_INDIVIDUAL';

// 일괄 업로드
export const CUSTOMER_UPLOAD_SAVE_DRAFT = 'CUSTOMER_UPLOAD_SAVE_DRAFT';
export const COMPANY_UPLOAD_SAVE_DRAFT = 'COMPANY_UPLOAD_SAVE_DRAFT';
