// 법무법인 관리
export const LAWFIRM_MNG_SET_REDUX_VALUES = 'LAWFIRM_MNG_SET_REDUX_VALUES';
export const LAWFIRM_MNG_FETCH_BY_LAWFIRM_ID = 'LAWFIRM_MNG_FETCH_BY_LAWFIRM_ID';
export const LAWFIRM_MNG_UPDATE = 'LAWFIRM_MNG_UPDATE';

// 코드 관리
export const LAWFIRM_MNG_CODE_MNG_FETCH_GROUPLIST = 'LAWFIRM_MNG_CODE_MNG_FETCH_GROUPLIST';
export const LAWFIRM_MNG_CODE_MNG_FETCH_CODELIST = 'LAWFIRM_MNG_CODE_MNG_FETCH_CODELIST';
export const LAWFIRM_MNG_CODE_MNG_SET_SELECT = 'LAWFIRM_MNG_CODE_MNG_SET_SELECT';
export const LAWFIRM_MNG_CODE_MNG_SAVE_DRAFT = 'LAWFIRM_MNG_CODE_MNG_SAVE_DRAFT';
export const LAWFIRM_MNG_CODE_MNG_CHECK_INPUT = 'LAWFIRM_MNG_CODE_MNG_CHECK_INPUT';

// 사건 관리
export const LAWFIRM_MNG_CASE_FETCH_VALUES = 'LAWFIRM_MNG_CASE_FETCH_VALUES';
export const LAWFIRM_MNG_CASE_SAVE_DRAFT = 'LAWFIRM_MNG_CASE_SAVE_DRAFT';
