export const CONSULTATION_MNG_SET_REDUX_VALUES = 'CONSULTATION_MNG_SET_REDUX_VALUES';
export const CONSULTATION_MNG_PUSH_VALUES = 'CONSULTATION_MNG_PUSH_VALUES';
export const CONSULTATION_MNG_REMOVE_VALUES = 'CONSULTATION_MNG_REMOVE_VALUES';

export const CONSULTATION_MNG_CHECK_INPUT = 'CONSULTATION_MNG_CHECK_INPUT';
export const CONSULTATION_MNG_SAVE_DRAFT = 'CONSULTATION_MNG_SAVE_DRAFT';
export const CONSULTATION_MNG_SAVE_MANAGER = 'CONSULTATION_MNG_SAVE_MANAGER';
export const CONSULTATION_MNG_SAVE_RELATEDCASE_CONTRACT = 'CONSULTATION_MNG_SAVE_RELATEDCASE_CONTRACT';
export const CONSULTATION_MNG_SAVE_CLIENT = 'CONSULTATION_MNG_SAVE_CLIENT';
export const CONSULTATION_MNG_LIST_FETCH = 'CONSULTATION_MNG_LIST_FETCH';
export const CONSULTATION_MNG_DETAIL_BIND = 'CONSULTATION_MNG_DETAIL_BIND';
export const CONSULTATION_MNG_DELETE_FILE = 'CONSULTATION_MNG_DELETE_FILE';
export const CONSULTATION_MNG_DELETE_DATA = 'CONSULTATION_MNG_DELETE_DATA';

export const CONSULTATION_MNG_SET_CASELIST = 'CONSULTATION_MNG_SET_CASELIST';
export const CONSULTATION_MNG_SET_CONTRACTLIST = 'CONSULTATION_MNG_SET_CONTRACTLIST';
export const CONSULTATION_MNG_MAPPING_CASE_CONTRACT = 'CONSULTATION_MNG_MAPPING_CASE_CONTRACT';

export const CONSULTATION_MNG_CLEAR_SAVE_DATA = 'CONSULTATION_MNG_CLEAR_SAVE_DATA';
