export const NOTICEMNG_SET_REDUX_VALUES = 'NOTICEMNG_SET_REDUX_VALUES';

export const NOTICEMNG_SAVE_DRAFT = 'NOTICEMNG_SAVE_DRAFT';
export const NOTICEMNG_CHECK_INPUT_DATA = 'NOTICEMNG_CHECK_INPUT_DATA';
export const NOTICEMNG_LIST_FETCH = 'NOTICEMNG_LIST_FETCH';
export const NOTICEMNG_DETAIL_BIND = 'NOTICEMNG_DETAIL_BIND';
export const NOTICEMNG_DELETE_DATA = 'NOTICEMNG_DELETE_DATA';
export const NOTICEMNG_SET_SELECT = 'NOTICEMNG_SET_SELECT';
