export const CASE_SET_REDUX_VALUES = 'CASE_SET_REDUX_VALUES';

// CASE_MEMO
export const CASE_MEMO_SAVE_DRAFT = 'CASE_MEMO_SAVE_DRAFT';
export const CASE_MEMO_LIST_SEARCH = 'CASE_MEMO_LIST_SEARCH';
export const CASE_MEMO_DETAIL_BIND = 'CASE_MEMO_DETAIL_BIND';
export const CASE_MEMO_DELETE_DATA = 'CASE_MEMO_DELETE_DATA';
export const CASE_MEMO_CHECK_INPUT_DATA = 'CASE_MEMO_CHECK_INPUT_DATA';

// CASE_List
export const CASE_LIST_FETCH = 'CASE_LIST_FETCH';
export const CASE_LIST_SET_DETAIL_BIND = 'CASE_LIST_SET_DETAIL_BIND';
export const CASE_LIST_HANDLE_CONTRACT_ID = 'CASE_LIST_HANDLE_CONTRACT_ID';
export const CASE_LIST_FETCH_CONTRACT_LIST = 'CASE_LIST_FETCH_CONTRACT_LIST';
export const CASE_LIST_SET_SELECT = 'CASE_LIST_SET_SELECT';

// CASE_DueDate
export const CASE_DUEDATE_LIST_FETCH = 'CASE_DUEDATE_LIST_FETCH';
export const CASE_DUEDATE_CHECK_INPUT_DATA = 'CASE_DUEDATE_CHECK_INPUT_DATA';
export const CASE_DEUDATE_SAVE_DRAFT = 'CASE_DEUDATE_SAVE_DRAFT';
export const CASE_DUEDATE_DETAIL_BIND = 'CASE_DUEDATE_DETAIL_BIND';
export const CASE_DUEDATE_SET_SELECT = 'CASE_DUEDATE_SET_SELECT';
export const CASE_DUEDATE_DELETE_DATA = 'CASE_DUEDATE_DELETE_DATA';
export const CASE_DUEDATE_DELETE_FILE = 'CASE_DUEDATE_DELETE_FILE';

// CASE_Create
export const CASE_CREATE_DETAIL_BIND = 'CASE_CREATE_DETAIL_BIND';
export const CASE_CREATE_CHECK_INPUT_DATA = 'CASE_CREATE_CHECK_INPUT_DATA';
export const CASE_CREATE_SAVE_DRAFT = 'CASE_CREATE_SAVE_DRAFT';
export const CASE_CREATE_DELETE_FILE = 'CASE_CREATE_DELETE_FILE';
export const CASE_CREATE_DELETE_CASE = 'CASE_CREATE_DELETE_CASE';
export const CASE_CREATE_HANDLE_PERFORMER = 'CASE_CREATE_HANDLE_PERFORMER';
export const CASE_CREATE_HANDLE_PARTY = 'CASE_CREATE_HANDLE_PARTY';

// CASE_DETAIL_CASEINFO 초기화 (DIALOG 용)
export const CASE_CLEAR_CASE_INFO = 'CASE_CLEAR_CASE_INFO';

// CASE_TC
export const CASE_TC_LIST_FETCH = 'CASE_TC_LIST_FETCH';
export const CASE_TC_DETAIL_BIND_FETCH = 'CASE_TC_DETAIL_BIND_FETCH';
export const CASE_TC_DETAIL_BIND = 'CASE_TC_DETAIL_BIND';
export const CASE_TC_MODIFY = 'CASE_TC_MODIFY';
export const CASE_TC_DELETE = 'CASE_TC_DELETE';
export const CASE_TC_CLEAR_DATA = 'CASE_TC_CLEAR_DATA';
