// 문서 관리
export const DOCUMENT_MNG_SET_REDUX_VALUES = 'DOCUMENT_MNG_SET_REDUX_VALUES';
export const DOCUMENT_MNG_FETCH = 'DOCUMENT_MNG_FETCH';
export const DOCUMENT_MNG_SAVE = 'DOCUMENT_MNG_SAVE';
export const DOCUMENT_MNG_DELETE = 'DOCUMENT_MNG_DELETE';
export const DOCUMENT_MNG_HANDLE_CHANGE = 'DOCUMENT_MNG_HANDLE_CHANGE';
export const DOCUMENT_MNG_CLEAR_FILE_LIST = 'DOCUMENT_MNG_CLEAR_FILE_LIST';
export const DOCUMENT_MNG_CLEAR_DIALOG_DATA = 'DOCUMENT_MNG_CLEAR_DIALOG_DATA';
export const DOCUMENT_MNG_CLEAR_ALL_DATA = 'DOCUMENT_MNG_CLEAR_ALL_DATA';
export const DOCUMENT_MNG_HANDLE_CONTRACT_LIST_FETCH = 'DOCUMENT_MNG_HANDLE_CONTRACT_LIST_FETCH';
export const DOCUMENT_MNG_HANDLE_CONTRACT_FILE_FETCH = 'DOCUMENT_MNG_HANDLE_CONTRACT_FILE_FETCH';
export const DOCUMENT_MNG_HANDLE_CONSULT_LIST_FETCH = 'DOCUMENT_MNG_HANDLE_CONSULT_LIST_FETCH';
export const DOCUMENT_MNG_HANDLE_CONSULT_FILE_FETCH = 'DOCUMENT_MNG_HANDLE_CONSULT_FILE_FETCH';
export const DOCUMENT_MNG_HANDLE_CASE_LIST_FETCH = 'DOCUMENT_MNG_HANDLE_CASE_LIST_FETCH';
export const DOCUMENT_MNG_HANDLE_CASE_FILE_FETCH = 'DOCUMENT_MNG_HANDLE_CASE_FILE_FETCH';
export const DOCUMENT_MNG_HANDLE_DUEDATE_LIST_FETCH = 'DOCUMENT_MNG_HANDLE_DUEDATE_LIST_FETCH';
export const DOCUMENT_MNG_HANDLE_DUEDATE_FILE_FETCH = 'DOCUMENT_MNG_HANDLE_DUEDATE_FILE_FETCH';
