// 유저 관리
export const USERMNG_SET_REDUX_VALUES = 'USERMNG_SET_REDUX_VALUES';
export const USERMNG_SET_LIST_FETCH = 'USERMNG_SET_LIST_FETCH';
export const USERMNG_SET_DETAIL_BIND = 'USERMNG_SET_DETAIL_BIND';
export const USERMNG_SET_ROLECODE = 'USERMNG_SET_ROLECODE';
export const USERMNG_SAVE_DRAFT = 'USERMNG_SAVE_DRAFT';
export const USERMNG_CHECK_EMAIL = 'USERMNG_CHECK_EMAIL';
export const USERMNG_CHECK_INPUT_DATA = 'USERMNG_CHECK_INPUT_DATA';
export const USERMNG_UPDATE_PHOTOURL = 'USERMNG_UPDATE_PHOTOURL';
export const USERMNG_SET_SELECT = 'USERMNG_SET_SELECT';

// 유저 그룹 관리
export const USERGROUPMNG_SAVE_DRAFT = 'USERGROUPMNG_SAVE_DRAFT';
export const USERGROUPMNG_CHECK_INPUT = 'USERGROUPMNG_CHECK_INPUT';
export const USERGROUPMNG_LIST_FETCH = 'USERGROUPMNG_LIST_FETCH';
export const USERGROUPMNG_DETAIL_BIND = 'USERGROUPMNG_DETAIL_BIND';
export const USERGROUPMNG_SET_SELECT = 'USERGROUPMNG_SET_SELECT';